In [43]:
import pandas as pd
import requests

In [44]:
url = "https://data.cdc.gov/resource/i46a-9kgh.json"
params = {
    "$select": "stateabbr,countyname,countyfips,BINGE_AdjPrev",
    "stateabbr": "CA"
}

r = requests.get(url, params = params)
r.raise_for_status()

binge_ca = pd.DataFrame(r.json())

In [45]:

binge_ca.rename(columns={'countyname': 'County'}, inplace=True)
binge_ca.head()

  stateabbr  County countyfips BINGE_AdjPrev
0        CA  Solano      06095          16.3
1        CA  Placer      06061          18.7
2        CA   Kings      06031          16.9
3        CA  Fresno      06019          14.5
4        CA  Amador      06005          19.9

In [46]:
income_path = "../data/raw/us_income.csv"

income_df = pd.read_csv(income_path)
display(income_df.head(5))

cali_df = income_df[income_df['State'] == 'California']
display(cali_df.head(5))

cali_df['County'] = cali_df['County'].apply(lambda x: x[:len(x)-7])

cali_df['FIPS'] = cali_df['FIPS'].apply(lambda x: "0" + str(x))

print(cali_df.shape)

,County,State,FIPS,State FIPS Code,County FIPS Code,Total Population,Median Household Income,Urban-Rural
0,Autauga County,Alabama,1001,1,1,59285,69841,Urban
1,Baldwin County,Alabama,1003,1,3,239945,75019,Urban
2,Barbour County,Alabama,1005,1,5,24757,44290,Rural
3,Bibb County,Alabama,1007,1,7,22152,51215,Rural
4,Blount County,Alabama,1009,1,9,59292,61096,Urban

,County,State,FIPS,State FIPS Code,County FIPS Code,Total Population,Median Household Income,Urban-Rural
187,Alameda County,California,6001,6,1,1651949,126240,Urban
188,Alpine County,California,6003,6,3,1695,110781,Rural
189,Amador County,California,6005,6,5,41029,81526,Urban
190,Butte County,California,6007,6,7,209470,68574,Urban
191,Calaveras County,California,6009,6,9,45995,79877,Urban

(58, 8)

In [47]:
display(cali_df.head(5))
binge_ca.head()

,County,State,FIPS,State FIPS Code,County FIPS Code,Total Population,Median Household Income,Urban-Rural
187,Alameda,California,06001,6,1,1651949,126240,Urban
188,Alpine,California,06003,6,3,1695,110781,Rural
189,Amador,California,06005,6,5,41029,81526,Urban
190,Butte,California,06007,6,7,209470,68574,Urban
191,Calaveras,California,06009,6,9,45995,79877,Urban

  stateabbr  County countyfips BINGE_AdjPrev
0        CA  Solano      06095          16.3
1        CA  Placer      06061          18.7
2        CA   Kings      06031          16.9
3        CA  Fresno      06019          14.5
4        CA  Amador      06005          19.9

In [52]:
df = pd.merge(cali_df, binge_ca, on='County')
display(df.head())
df = df.loc[:, ['County', 'stateabbr', 'countyfips', 'BINGE_AdjPrev', 'Median Household Income']]
df.head()

,County,State,FIPS,State FIPS Code,County FIPS Code,Total Population,Median Household Income,Urban-Rural,stateabbr,countyfips,BINGE_AdjPrev
0,Alameda,California,06001,6,1,1651949,126240,Urban,CA,06001,16.3
1,Alpine,California,06003,6,3,1695,110781,Rural,CA,06003,20.0
2,Amador,California,06005,6,5,41029,81526,Urban,CA,06005,19.9
3,Butte,California,06007,6,7,209470,68574,Urban,CA,06007,18.8
4,Calaveras,California,06009,6,9,45995,79877,Urban,CA,06009,19.3

      County stateabbr countyfips BINGE_AdjPrev  Median Household Income
0    Alameda        CA      06001          16.3                   126240
1     Alpine        CA      06003          20.0                   110781
2     Amador        CA      06005          19.9                    81526
3      Butte        CA      06007          18.8                    68574
4  Calaveras        CA      06009          19.3                    79877

In [53]:
df.describe()

       Median Household Income
count                58.000000
mean              87001.137931
std               25546.764494
min               53498.000000
25%               67888.500000
50%               80701.500000
75%              102701.250000
max              159674.000000

In [54]:
print(df.shape)

(58, 5)

In [55]:
output_file = '../data/interim/combined_data.csv'
df.to_csv(
    output_file,
    index=False,
    encoding="utf-8"
)

print(f"Output file: {output_file}")

Output file: ../data/interim/combined_data.csv